jQuery(function($){$("#payment-method").chosen({disable_search:true,inherit_select_classes:true});jQuery("#coupone_slider_head").click(function(){if(jQuery("#coupone_slider_content").css("display")=="none"&&jQuery(".msg-for-coupone").css("display")=="block")jQuery(".msg-for-coupone").slideToggle(150);jQuery("#coupone_slider_content").slideToggle(150);jQuery("#coupon_code").focus()});jQuery("#opcheckout-order-comment-label").click(function(){jQuery("#opcheckout-order-comment-wrap").slideToggle(150);
jQuery("#opcheckout_order_comment").focus()});jQuery("#opcheckout_order_comment").on("keyup",function(){jQuery("#hidden_opcheckout_order_comment").val(jQuery(this).val())});jQuery(".checkout-scroll-block").mCustomScrollbar({theme:"dark-thick",mouseWheelPixels:"400",scrollInertia:250,advanced:{updateOnContentResize:true,updateOnBrowserResize:true},scrollButtons:{enable:false}});(function(){var inpt=$("#billing\\:telephone, #billing\\:telephone-2");if(!inpt.length)return;var val=inpt.val().trim().replace(/\s\(\)/,
"");inpt.focus(function(){if(inpt.val()==""){var val=38;inpt.val(val)}});inpt.inputmask("+99 999 999-99-99",{"placeholder":"",showMaskOnHover:false,disablePredictiveText:true,jitMasking:true});inpt.val(val)})()});function changeItemQtyOrRemove(itemIndex,value,deleted,productId){window.quoteItems.changeItemQtyOrRemove(itemIndex,value,deleted,productId)}
function checkoutCartRerender(){var minQty=0;var maxQty=99;var isSpinStopped=false;jQuery(".spinner").spinner({max:maxQty,min:minQty,numberFormat:"n",spin:function(event,ui){if(isSpinStopped)event.preventDefault();isSpinStopped=true},stop:function(event,ui){that=this;setTimeout(function(){changeItemQtyOrRemove(jQuery(that).attr("data-item-index"),jQuery(that).attr("aria-valuenow"),jQuery(that).attr("data-deleted"),jQuery(that).data("product-id"))},20);isSpinStopped=false}});jQuery(".ui-spinner-input").each(function(index,
value){if(jQuery(value).val()<=minQty)jQuery(value).parent().find(".ui-spinner-down").addClass("disabled");else if(jQuery(value).val()==maxQty)jQuery(value).parent().find(".ui-spinner-up").addClass("disabled");else{jQuery(value).parent().find(".ui-spinner-down").removeClass("disabled");jQuery(value).parent().find(".ui-spinner-up").removeClass("disabled")}});jQuery("input.opcheckout-item-qty").unbind("input");jQuery("input.opcheckout-item-qty").on("input",function(element,ui){changeItemQtyOrRemove(jQuery(this).attr("data-item-index"),
jQuery(this).val(),jQuery(this).attr("data-deleted"),jQuery(this).data("product-id"))});jQuery("input.opcheckout-item-qty").unbind("click");$$(".opcheckout-item-remove").each(function(el){el.observe("click",function(){quoteItems.removeItem(jQuery(el).attr("data-item-index"))})});jQuery(".checkout-scroll-block").mCustomScrollbar({theme:"dark-thick",mouseWheelPixels:"400",scrollInertia:250,advanced:{updateOnContentResize:true,updateOnBrowserResize:true},scrollButtons:{enable:false}});jQuery(document).ready(function(){var checkoutSBlockHeight=
jQuery(".checkout-scroll-block").height();var headerHeight=jQuery(".header").height();var productItemHeight=jQuery("#checkout-product-container li").outerHeight(true);var productQty=jQuery("#checkout-product-container li").length;var paddingTop=parseInt(jQuery("#checkout-product-container").css("padding-top"));var totalsHeight=jQuery("#one-step-checkout-review .total").outerHeight(true);var maxHeight=jQuery(window).height()-totalsHeight-headerHeight-20;if(checkoutSBlockHeight>maxHeight){var maxProductQty=
Math.floor((maxHeight-paddingTop)/productItemHeight);var needleHeight;if(maxProductQty<productQty)needleHeight=maxProductQty*productItemHeight;else needleHeight=productQty*productItemHeight;jQuery(".checkout-scroll-block").height(needleHeight+paddingTop)}setMinHeightForContainer()});function setMinHeightForContainer(){setTimeout(function(){var mainContainer=jQuery("#main").children(".main-container");var checkoutSidebar=jQuery("#one-step-checkout-review");var checkoutSidebarScrolBlock=checkoutSidebar.find(".checkout-scroll-block");
var checkoutSidebarHeading=checkoutSidebar.find(".heading");var checkoutSidebarTotal=checkoutSidebar.find(".total");var minHeightBasedOnSidebar=checkoutSidebarScrolBlock.outerHeight()+checkoutSidebarHeading.outerHeight()+checkoutSidebarTotal.outerHeight()+30;mainContainer.css("min-height",minHeightBasedOnSidebar)},10)}};
