if(typeof Product!="undefined"){var cswatch={defaultOptions:{width:35,height:35,label:true,labelWithPrice:false,title:true,titleWithPrice:false,selected:null,type:"default",removeAllThumbnails:true},holderOptions:{color:{label:false,selected:0,type:"grid"},volume:{type:"default",selected:0}},getObjectLength:function(obj){var l=0,key;for(key in obj)if(obj.hasOwnProperty(key))l++;return l},getAttributeHolder:function(options){var key=options.prefix+"-"+options.attrCode;var holder=this._holders[key];
if(!holder){holder=jQuery("#"+key);var selectHolder=jQuery(options.select).parent();if(!holder.length){holder=jQuery("<ul/>").appendTo(selectHolder).attr("id",key).addClass("cswatch-attribute");if(options.attrCode=="color")jQuery(options.select).hide()}else selectHolder.closest("dd").hide().prev("dt").hide();var holderOptions=cswatch.holderOptions[options.attrCode];switch(holderOptions.type){case "grid":this.attachEvent(holder,options);break;default:this.attachEventToDropdown(holder,options);break}this._holders[key]=
holder}return holder},moveSelectTo:function(holder,el,selected){var select=jQuery(el).appendTo(holder);jQuery(function(){select.find("option").eq(selected).prop("selected",true);fireEvent(el,"change")})},attachEvent:function(holder,options){holder.off("click").on("click","a",function(){var link=jQuery(this),liItem=link.parent();if(!liItem.is(".active")){holder.find("li.active").removeClass("active");liItem.addClass("active");var option=link.data("option");jQuery(options.select).find("option[value="+
option.id+"]").prop("selected",true);fireEvent(options.select,"change");jQuery("#cswatch-volume select").chosen({disable_search:true});if(callback=cswatch.holderOptions[options.attrCode])if(typeof callback.onChange==="function")callback.onChange(holder,option);if(options.prefix==="cswatch")cswatch.renderMediaGallery(options.attrId,option.id)}})},attachEventToDropdown:function(holder,options){jQuery(options.select).off("change").on("change",function(){if(callback=cswatch.holderOptions[options.attrCode])if(typeof callback.onChange===
"function")callback.onChange(holder,options)})},renderMediaGallery:function(attrId,optionId){var gallery=this.getMediaGalleryItems(attrId,optionId),holder=this.getMoreViewsHolder(),holderItems=holder.children(),cache={};if(gallery&&gallery.length){holderItems.filter(".simple").remove();var isDefault=false;jQuery.each(gallery,function(){var item=jQuery("<li/>").appendTo(holder).addClass("simple");var link=jQuery("<a/>").appendTo(item).attr({href:this.base}).attr("data-small",this.small);jQuery("<img/>").appendTo(link).attr({src:this.thumbnail});
if(this.is_default){jQuery(function(){item.trigger("click")});isDefault=true}});if(!isDefault)jQuery(function(){holder.find("li:visible:first").trigger("click")})}if(this.defaultOptions.removeAllThumbnails)holderItems.not(".simple").remove()},getMediaGalleryItems:function(attrId,optionId){var mg=this._mediaGallery;if(mg[attrId]&&(gallery=mg[attrId][optionId]))return gallery;return false},getMoreViewsHolder:function(){if(!this._holders.mv)this._holders.mv=jQuery("#more_views ul.thumbnails");return this._holders.mv},
_mediaGallery:{},_holders:{},_node:{},_cache:{}};var __fillSelect=function(element){var attributeId=element.id.replace(/[a-z]*/,"");var options=this.getAttributeOptions(attributeId);this.clearSelect(element);element.options[0]=new Option(this.config.chooseText,"");var prevConfig=false;if(element.prevSetting)prevConfig=element.prevSetting.options[element.prevSetting.selectedIndex];options.sort(function(a,b){return a.position-b.position});var attributeCode=this.config.attributes[attributeId].code;var prefix=
jQuery(element).data("swatchprefix")||"cswatch";var holder=cswatch.getAttributeHolder({attrId:attributeId,attrCode:attributeCode,select:element,prefix:prefix,attributes:this.config.attributes});var holderOptions=jQuery.extend({},cswatch.defaultOptions,cswatch.holderOptions[attributeCode]||{});if(holder.length)holder.html("").show();if(!cswatch.defaultOptions.mediaUrl)cswatch.defaultOptions.mediaUrl=this.config.attributes[attributeId].mediaUrl;if(options){var index=1;for(var i=0;i<options.length;i++){var allowedProducts=
[];if(prevConfig)for(var j=0;j<options[i].products.length;j++){if(prevConfig.config.allowedProducts&&prevConfig.config.allowedProducts.indexOf(options[i].products[j])>-1)allowedProducts.push(options[i].products[j])}else allowedProducts=options[i].products.clone();if(allowedProducts.size()>0){options[i].allowedProducts=allowedProducts;element.options[index]=new Option(this.getOptionLabel(options[i],options[i].price),options[i].id);element.options[index].config=options[i];if(holder.length){switch(holderOptions.type){default:break;
case "dropdown":break;case "grid":var listItem=jQuery("<li/>").appendTo(holder);var mediaGallery=options[i].mediaGallery&&options[i].mediaGallery.length?options[i].mediaGallery:0;if(typeof options[i].mana=="object"){var link=jQuery("<a/>").appendTo(listItem).addClass("cswatch-item-"+options[i].id).data("option",options[i]);var item=jQuery("<span class='color-item'>").appendTo(link).width(holderOptions.width).height(holderOptions.height);if(options[i].mediaGallery&&options[i].mediaGallery.length){if(!cswatch._mediaGallery[attributeId])cswatch._mediaGallery[attributeId]=
[];if(!cswatch._mediaGallery[attributeId][options[i].id])cswatch._mediaGallery[attributeId][options[i].id]=options[i].mediaGallery}if(options[i].mana.image)item.css("background-image","url("+options[i].mana.image+")");else if(options[i].mana.color)item.css("background-color",options[i].mana.color);if(holderOptions.label||holderOptions.title){var onlyLabel=options[i].label,withPrice=null;if(holderOptions.labelWithPrice||holderOptions.titleWithPrice)withPrice=onlyLabel+" "+(options[i].price>0?this.formatPrice(options[i].price,
true):null);if(holderOptions.label)item.html(holderOptions.labelWithPrice?withPrice:onlyLabel);if(holderOptions.title)item.attr("title",holderOptions.titleWithPrice?withPrice:onlyLabel)}}break}if(options[i].is_default)holderOptions.selected=listItem.index()}index++}}if(holderOptions.type==="default"){element.options[0].remove();cswatch.moveSelectTo(holder,element,holderOptions.selected)}}if(holderOptions.selected!=null)jQuery(function(){holder.find("a").eq(holderOptions.selected).trigger("click")})};
var __reloadOptionLabels=function(element){var selectedPrice;if(element.options[element.selectedIndex].config)selectedPrice=parseFloat(element.options[element.selectedIndex].config.price);else selectedPrice=0;for(var i=0;i<element.options.length;i++)if(element.options[i].config)element.options[i].text=this.getOptionLabel(element.options[i].config,element.options[i].config.price-selectedPrice)};Product.Config.prototype.fillSelect=__fillSelect;Product.Config.prototype.reloadOptionLabels=__reloadOptionLabels};
