window.intPrevious=setInterval(function(){if(typeof AW_ACP!="undefined"&&document.body){if(typeof aw_cartDivClass=="undefined"){aw_cartDivClass=AW_ACP.theme=="blank"?".block-cart":".mini-cart";if(!$$(aw_cartDivClass).length||!$$(aw_cartDivClass)[0].tagName)aw_cartDivClass=".block-cart"}if(typeof aw_topLinkCartClass=="undefined")aw_topLinkCartClass=".top-link-cart";if(typeof aw_addToCartButtonClass=="undefined")aw_addToCartButtonClass=".form-button";if(typeof aw_bigCartClass=="undefined")if(typeof $$(".layout-1column")[0]!=
"undefined")aw_bigCartClass=".layout-1column";else if(typeof $$(".col-main")[0]!="undefined")aw_bigCartClass=".col-main";else aw_bigCartClass=".cart";if(typeof aw_wishlistClass=="undefined")if(typeof $$(".my-wishlist")[0]!="undefined")aw_wishlistClass=".my-wishlist";else aw_wishlistClass=".padder";if(typeof aw_wishlistSidebarClass=="undefined")aw_wishlistSidebarClass=".block-wishlist";if(typeof aw_topWishlistLinkCartClass=="undefined")if($$(".top-link-wishlist a").length)aw_topWishlistLinkCartClass=
".top-link-wishlist a";else aw_topWishlistLinkCartClass=".top-link-wishlist";if(window.location.toString().search("/product_compare/")!=-1)win=window.opener;else win=window;clearInterval(intPrevious)}},500);
var AWC={is_open:false,fl_is_open:false,updateQty:function(params){if(this.timer)clearTimeout(this.timer);if(!this.url)this.url=AW_ACP.cartURL.replace("checkout/cart/","ajaxcart/cart/updateqty");this.timer=setTimeout(function(){if(AWC._request){AWC._request.transport.abort();AWC.hideOverlay()}AWC._request=new Ajax.Request(AWC.url,{method:"post",parameters:{id:params.quote,qty:params.qty,action:"cartplus"},onCreate:function(){},onSuccess:function(transport){if(transport.status==200){var response=transport.responseText.evalJSON();
params.input.val(response.quantity);updateCartView(response);if(AWC.fl_is_open)AWC.updateFloatingCart(response.total)}},onComplete:function(){hideProgressAnimation()}})},500)},openCartSidebar:function(){AWC.hideOverlay();AWC.is_open=true;jQuery("#cart_holder").find(".cart-content").show();jQuery("#cart_holder").find(".total-block").show();jQuery("#cart_holder").find(".btn-holder").show();jQuery("#cart_holder").find(".recommended").show();var holder=jQuery("#cart_holder").addClass("popup-active");
var close=holder.find(".cancel, .close").off("click");close.on("click",function(e){e.preventDefault();AWC.closeCartSidebar();AWC.is_open=false});setCartContentHeight()},closeCartSidebar:function(){jQuery("#cart_holder.popup-active").removeClass("popup-active");AWC.is_open=false},openFloatingCart:function(content){AWC.fl_is_open=true;var wait=jQuery("#floating-cart-wait").hide();var content=jQuery("#floating-cart-content").show().html(content);var holder=jQuery("#floating-cart-holder");var close=holder.find(".close");
close.off("click").on("click",function(e){e.preventDefault();AWC.closeFloatingCart()})},openPreparedFloatingCart:function(){AWC.showOverlay();AWC.fl_is_open=true;jQuery("#floating-cart-content").hide();jQuery("#floating-cart-wait").show();jQuery("#floating-cart-holder").addClass("popup-active")},updateFloatingCart:function(total){jQuery("#floating-cart-total").html(total)},closeFloatingCart:function(){jQuery(".popup-active").removeClass("popup-active");AWC.fl_is_open=false},showOverlay:function(){jQuery(".ajaxcart-overlay").show()},
hideOverlay:function(){jQuery(".ajaxcart-overlay").attr("style","top: 0; bottom: 0;").hide()},inc:function(quote,ctrl){var input=jQuery(ctrl).parent().find("input");var qty=+input.val();if(qty<=99){input.val(++qty);showProgressAnimation();this.updateQty({"qty":qty,"quote":quote,"input":input})}if(qty==99)input.parents(".product-counter").find(".ui-spinner-up").addClass("disabled");else input.parents(".product-counter").find(".ui-spinner-up").removeClass("disabled");if(qty==1)input.parents(".product-counter").find(".ui-spinner-down").addClass("disabled");
else input.parents(".product-counter").find(".ui-spinner-down").removeClass("disabled")},dec:function(quote,ctrl){var input=jQuery(ctrl).parent().find("input");var qty=+input.val();if(qty>1){input.val(--qty);showProgressAnimation();this.updateQty({"qty":qty,"quote":quote,"input":input})}if(qty==1)input.parents(".product-counter").find(".ui-spinner-down").addClass("disabled");else input.parents(".product-counter").find(".ui-spinner-down").removeClass("disabled");if(qty==99)input.parents(".product-counter").find(".ui-spinner-up").addClass("disabled");
else input.parents(".product-counter").find(".ui-spinner-up").removeClass("disabled")},update:function(quote,input){var input=jQuery(input);var qty=+input.val()||1;if(qty<=0)qty=0;else if(qty>99)qty=99;showProgressAnimation();this.updateQty({"qty":qty,"quote":quote,"input":input})},checkout:function(url){AWC.closeFloatingCart();setLocation(url)},init:function(resp){if(AWC.is_open)AWC.openCartSidebar()},updateRequestUrl:function(url,obj){var obj=jQuery(obj).closest("li.item").find("input[name*='qty']"),
qty=1;if(obj.length){var objVal=parseInt(obj.val());qty=objVal>0?objVal:qty;return url+"/qty/"+qty}return url}};jQuery(function(){jQuery("a.top-link-cart").on("click",function(e){e.preventDefault();AWC.openCartSidebar();return false});jQuery(window).on("resize",setCartContentHeight)});
function setCartContentHeight(){if(jQuery(window).height()>790&&jQuery(window).height()<=850){jQuery("#cart_holder").find(".recommended").show();jQuery("#cart_holder").find(".recommended").attr("style","height: auto;");jQuery("#cart_holder").find(".recommended").find("li:nth-child(2)").show();jQuery("#cart_holder").find(".recommended").find("li:nth-child(3)").hide()}else if(jQuery(window).height()>600&&jQuery(window).height()<=790){jQuery("#cart_holder").find(".recommended").show();jQuery("#cart_holder").find(".recommended").attr("style",
"height: auto;");jQuery("#cart_holder").find(".recommended").find("li:nth-child(2)").hide();jQuery("#cart_holder").find(".recommended").find("li:nth-child(3)").hide()}else if(jQuery(window).height()>0&&jQuery(window).height()<=600){jQuery("#cart_holder").find(".recommended").hide();jQuery("#cart_holder").find(".recommended").height(0)}else{jQuery("#cart_holder").find(".recommended").show();jQuery("#cart_holder").find(".recommended").attr("style","height: auto;");jQuery("#cart_holder").find(".recommended").find("li:nth-child(2)").show();
jQuery("#cart_holder").find(".recommended").find("li:nth-child(3)").show()}var cartHolder=jQuery("#cart_holder");var cartBlock=cartHolder.find(".cart-block");var cartScrollBlock=cartHolder.find(".cart-scroll-block");var cartCheckContainer=cartBlock.children(".cart-checkout-container");var cartProdContainer=cartHolder.find("#cart-product-container");var cartRecommended=cartHolder.find(".dp-widget-container");var cartContentHeight=jQuery(window).outerHeight()-cartHolder.find(".heading").outerHeight()-
cartCheckContainer.outerHeight();cartScrollBlock.css("height","auto");cartCheckContainer.css("position","static");if((cartRecommended.length||cartProdContainer.find("li").length>2)&&cartHolder.outerHeight()<cartBlock.outerHeight()-cartRecommended.outerHeight()){cartScrollBlock.css("height",cartContentHeight+"px");cartCheckContainer.css("position","absolute")}cartScrollBlock.mCustomScrollbar({theme:"dark-thick",setWidth:false,mouseWheelPixels:"400",scrollInertia:250,advanced:{updateOnContentResize:true,
updateOnBrowserResize:true},scrollButtons:{enable:false}})}
function ajaxcartdelete(url,callback){showProgressAnimation();url=getCommonUrl(url);if(typeof aw_acp_retries=="undefined")aw_acp_retries=0;new Ajax.Request(url,{onSuccess:function(resp){try{if(typeof resp.responseText=="string")eval("resp = "+resp.responseText)}catch(e){return}if(resp&&resp.error&&resp.error=="quote error"&&aw_acp_retries==0){aw_acp_retries=1;return ajaxcartdelete(url)}aw_acp_retries=0;hideProgressAnimation();__onACPRender();resp["delete"]=true;updateCartView(resp,callback);if(jQuery("#cart-product-container").find("li").not(".wish-message").length<=
0){AWC.closeCartSidebar();AWC.is_open=false}}})}
function updateCartBar(resp){var __cartObj=$$(aw_cartDivClass)[0];if(__cartObj){if(typeof __cartObj.length=="number")__cartObj=__cartObj[0];var oldHeight=__cartObj.offsetHeight;var tmpDiv=win.document.createElement("div");tmpDiv.innerHTML=resp.cartbar;$(tmpDiv).cleanWhitespace();var newCartData=parseNewCartData($(tmpDiv).select(aw_cartDivClass)[0]);jQuery("#cart_holder").find(".cart-scroll-block").replaceWith(newCartData.products);jQuery("#cart_holder").find(".total-block").replaceWith(newCartData.total);jQuery(".cart.block-cart").children().first().replaceWith(newCartData.quantity);
if(jQuery("#cart_holder").find(".recommended").length)jQuery("#cart_holder").find(".recommended").replaceWith(newCartData.recommended);else jQuery("#cart_holder").find(".cart-checkout-container").append(newCartData.recommended);var __cartObj=$$(aw_cartDivClass)[0];var newHeight=__cartObj.offsetHeight;addEffectACP(__cartObj,aw_ajaxcart_cartanim);truncateOptions()}updateDeleteLinks();updateTopLinks(resp);if(typeof resp.custom!="undefined")updateCustomBlocks(resp.custom)}
function parseNewCartData(node){var quantity=jQuery(node).children().first();var products=jQuery(node).find(".cart-scroll-block");var total=jQuery(node).find(".total-block");var recommended=jQuery(node).find(".recommended");return{quantity:quantity,products:products,total:total,recommended:recommended}}
function updateCartView(resp,callback){if(AW_ACP.isCartPage)return updateBigCartView(resp);var __cartObj=$$(aw_cartDivClass)[0];if(__cartObj){if(typeof __cartObj.length=="number")__cartObj=__cartObj[0];var oldHeight=__cartObj.offsetHeight;var tmpDiv=win.document.createElement("div");tmpDiv.innerHTML=resp.cart;$(tmpDiv).cleanWhitespace();var newCartData=parseNewCartData($(tmpDiv).select(aw_cartDivClass)[0]);jQuery("#cart_holder").find(".cart-scroll-block").replaceWith(newCartData.products);jQuery("#cart_holder").find(".total-block").replaceWith(newCartData.total);
jQuery(".cart.block-cart").children().first().replaceWith(newCartData.quantity);var lazyLinkBtn=jQuery(".cart.block-cart .btn-popup.lazy-link");if(lazyLinkBtn.length){var lazyLink=lazyLinkBtn.data("href");lazyLinkBtn.replaceTagName("a").attr("href",lazyLink).removeAttr("data-href").removeClass("lazy-link")}if(jQuery("#cart_holder").find(".recommended").length)jQuery("#cart_holder").find(".recommended").replaceWith(newCartData.recommended);else jQuery("#cart_holder").find(".cart-checkout-container").append(newCartData.recommended);
console.log(jQuery(resp.floating_cart).find(".extra"));jQuery("#cart_holder").find(".extra").replaceWith(jQuery(resp.floating_cart).find(".extra"));var __cartObj=$$(aw_cartDivClass)[0];var newHeight=__cartObj.offsetHeight;addEffectACP(__cartObj,aw_ajaxcart_cartanim);truncateOptions()}updateDeleteLinks();updateTopLinks(resp);if(typeof resp.custom!="undefined")updateCustomBlocks(resp.custom);AWC.init(resp);callback()}
function updateWishlist(resp){if(typeof resp.wishlist=="undefined")return;var wishlistObj=$$(aw_wishlistClass)[0];if(wishlistObj){var tmpDiv=win.document.createElement("div");tmpDiv.innerHTML=resp.wishlist;var tmpParent=wishlistObj.parentNode;tmpParent.replaceChild(tmpDiv.firstChild,wishlistObj)}var wishlistSidebar=$$(aw_wishlistSidebarClass).first();if(wishlistSidebar){wishlistSidebar.replace(resp.wishlist_sidebar);updateAddLinks()}};
