var cache={};jQuery(function($){cache.body=$("body");initDropDownClasses();initPopups();initChosen();initTooltip();initAnimateTo();initAlign();initCallback();initLearnbuying();initQuickOrder()});
(function($){$.fn.ydStickElement=function(options){var settings=$.extend({initBottom:undefined},options);var docHeight=$(document).height(),$win=$(window);function stickElementDetect($stickElement,elHeight,newTop,initTop){var scrollTop=$win.scrollTop(),currentElBottom=scrollTop+newTop+elHeight,currentMainBottom=docHeight-(settings.initBottom||0);if(currentElBottom<currentMainBottom)$stickElement.css("top",scrollTop+newTop);else $stickElement.css("top",currentMainBottom-elHeight-initTop)}return this.each(function(){var $stickElement=
$(this),initTop=parseInt($stickElement.css("top"));var elHeight=$stickElement.outerHeight(),newTop=$stickElement.offset().top-$stickElement.parent().offset().top;stickElementDetect($stickElement,elHeight,newTop,initTop||0);$win.on("scroll",function(){stickElementDetect($stickElement,elHeight,newTop,initTop||0)})})}})(jQuery);function initAlign(){var drop=jQuery("#drop-name");drop.css({marginLeft:-drop.outerWidth()/2})}
function initInputs(){PlaceholderInput.replaceByOptions({clearInputs:true,clearTextareas:true,clearPasswords:true,skipClass:"default",wrapWithElement:false,showUntilTyping:false,getParentByClass:false,placeholderAttr:"placeholder"})}
function initAnimateTo(){jQuery("a.animate-to").on("click",function(e){e.preventDefault();var self=jQuery(this),anchor=self.attr("href"),top;if(anchor.indexOf("#")==0){anchor=jQuery(anchor);if(anchor.length){top=anchor.offset().top-60;cache.body.animate({scrollTop:top},500)}}})}
function initDropDownClasses(){jQuery(".navigation li").each(function(){var item=jQuery(this);var drop=item.find("ul, div");var link=item.find("a").eq(0);if(drop.length){item.addClass("has-drop");if(link.length)link.addClass("has-drop-down-a")}})}
function initTooltip(){jQuery("a.btn-info").tooltip({tooltip:"span.tooltip"});jQuery("a.not-call-btn-info").tooltip({tooltip:"span.tooltip",extraOffsetX:-118,extraOffsetY:10,width:300});jQuery("a.create_account-info").tooltip({tooltip:"span.tooltip-create-account",extraOffsetX:-75,extraOffsetY:10,width:250});jQuery("a.reward-point-btn-info").tooltip({tooltip:"span.tooltip-rewards-point",extraOffsetX:-410,extraOffsetY:-150,width:330});jQuery("a.personal-discount-btn-info").tooltip({tooltip:"span.tooltip-personal-discount",
extraOffsetX:-380,extraOffsetY:-52,width:220});jQuery("a.gift-wrap-btn-info").tooltip({tooltip:"span.tooltip"});var shareWishlist=jQuery(".share-wishlist");shareWishlist.filter(".share-wishlist_right").tooltip({tooltip:".share-wishlist-tooltip",width:280,positionTypeX:"left",positionTypeY:"bottom",extraOffsetX:-130,extraOffsetY:20});shareWishlist.filter(".share-wishlist_center").tooltip({tooltip:".share-wishlist-tooltip",width:280,positionTypeX:"center",positionTypeY:"bottom",extraOffsetX:0,extraOffsetY:20});
jQuery(".info-certificate-title").tooltip({tooltip:".tooltip",positionTypeY:"bottom",positionTypeX:"center",extraOffsetX:-87,extraOffsetY:10,width:362,height:242});jQuery(".brands-menu-wrapper .order-probe-title").tooltip({tooltip:"span.tooltip",positionTypeY:"bottom",positionTypeX:"center",extraOffsetX:-12,extraOffsetY:10,width:false});jQuery(".stick-sidebar-wrapper span.order-probe-title").tooltip({tooltip:"span.tooltip",positionTypeY:"bottom",positionTypeX:"center",extraOffsetX:6,extraOffsetY:10,
width:165});jQuery("div.benefits .list li > a").tooltip()}function initChosen(){jQuery(".simple-select").chosen({disable_search:true,inherit_select_classes:true});jQuery(".custom-select").chosen({disable_search:true,inherit_select_classes:true})}
function initPopups(){if(window.matchMedia("screen and (max-width: 1024px)").matches){jQuery(".nav-popup").contentPopup({mode:"click",btnOpen:".all-links"});jQuery("#mobile-top-menu").contentPopup({mode:"click",btnOpen:".all-links",hideOnClickOutside:false});jQuery("#tel").contentPopup({mode:"click",btnOpen:"span.btn-open",openClass:"active",popup:".drop"});jQuery("#probe").contentPopup({mode:"click",btnOpen:".btn-open",openClass:"active",popup:".drop"})}else{jQuery(".nav-popup").contentPopup({mode:"hover",
btnOpen:".all-links"});jQuery("#mobile-top-menu").contentPopup({mode:"hover",btnOpen:".all-links"});jQuery("#brands-block").contentPopup({mode:"hover",btnOpen:"span",openClass:"active",btnClose:"a.btn-close",popup:".drop",delay:200});jQuery("#tel").contentPopup({mode:"hover",btnOpen:"span.btn-open",openClass:"active",popup:".drop"});jQuery("#probe").contentPopup({mode:"hover",btnOpen:".btn-open",openClass:"active",popup:".drop"});jQuery(".navigation > li.has-drop").contentPopup({mode:"hover",popup:".drop",
btnOpen:"> span",btnClose:"a.btn-close",openClass:"popup-active",delay:200,hideOnClickOutside:false})}jQuery("#user").contentPopup({mode:"click",btnOpen:"a.btn-user",openClass:"active",popup:".drop"})}
function initCallback(){var $callbacks=jQuery("#callbacks");$callbacks.find(".layout-close").on("click",function(e){e.preventDefault();jQuery(this).closest(".slide-popup").removeClass("popup-active")});jQuery("body").on("click",".callback-link",function(e){e.preventDefault();$callbacks.addClass("popup-active");$callbacks.find("#callbacks_name").focus()})}
function initQuickOrder(){var slide=jQuery("#quick-order");slide.find(".layout-close").on("click",function(e){e.preventDefault();jQuery(this).closest(".slide-popup").removeClass("popup-active")});jQuery("body").on("click",".quickorder-link",function(e){e.preventDefault();slide.addClass("popup-active");slide.find("#callbacks_name").focus()})}
function initLearnbuying(){var $learnbuying=jQuery("#learnbuying");$learnbuying.find(".layout-close").on("click",function(e){e.preventDefault();jQuery(this).closest(".slide-popup").removeClass("popup-active")});jQuery(".learnbuying-link").on("click",function(e){e.preventDefault();var productId=jQuery(this).data("id");jQuery("#learnbuying_product_id").val(productId);$learnbuying.addClass("popup-active");$learnbuying.find("#learnbuying_name").focus()})}
jQuery(function($){$(".fancybox").fancybox({autoSize:true,closeClick:true,openEffect:"fade",closeEffect:"fade"})});
jQuery(function($){$(".single-carousel .slideset").slick({infinite:true,speed:300,slidesToShow:1,slidesToScroll:1,slide:".slide",onInit:function(slick){var curImgHeight=$(slick.$slidesCache[slick.currentSlide]).find("img").height();slick.$slideTrack.css({height:curImgHeight})},onBeforeChange:function(event,currentSlide,nextSlide){var curImgHeight=$(this.$slidesCache[nextSlide]).find("img").height();this.$slideTrack.animate({height:curImgHeight},this.options.speed)}})});var menuStatus=false;
(function($){function ContentPopup(opt){this.options=$.extend({holder:null,popup:".popup",btnOpen:".open",btnClose:".close",openClass:"popup-active",clickEvent:"click",content:".columns",footer:".drop-brands",mode:"click",hideOnClickLink:true,hideOnClickOutside:true,delay:50},opt);if(this.options.holder){this.holder=$(this.options.holder);this.init()}}ContentPopup.prototype={init:function(){this.findElements();this.attachEvents()},findElements:function(){this.popup=this.holder.find(this.options.popup);
this.btnOpen=this.holder.find(this.options.btnOpen);this.btnClose=this.holder.find(this.options.btnClose)},findContents:function(){this.content=this.holder.find(this.options.content);this.footer=this.holder.find(this.options.footer)},attachEvents:function(){var self=this;this.clickMode=isTouchDevice||self.options.mode===self.options.clickEvent;if(this.clickMode){this.btnOpen.bind(self.options.clickEvent,function(e){if(self.holder.hasClass(self.options.openClass)){if(self.options.hideOnClickLink)self.hidePopup()}else self.showPopup();
e.preventDefault()});this.outsideClickHandler=this.bind(this.outsideClickHandler,this)}else{var timer,delayedFuncCloseSlow=function(func){clearTimeout(timer);timer=setTimeout(function(){menuStatus=false;func.call(self)},self.options.delay)},delayedFuncCloseFast=function(func){clearTimeout(timer);timer=setTimeout(function(){menuStatus=false;func.call(self)},self.options.delay/100)},delayedFuncOpenFast=function(func){clearTimeout(timer);timer=setTimeout(function(){menuStatus=true;func.call(self)},self.options.delay/
100)},delayedFuncOpenSlow=function(func){clearTimeout(timer);timer=setTimeout(function(){menuStatus=true;func.call(self)},self.options.delay/2)};this.btnOpen.bind("mouseover",function(){if(menuStatus)delayedFuncOpenFast(self.showPopup);else delayedFuncOpenSlow(self.showPopup)}).bind("mouseout",function(){delayedFuncCloseFast(self.hidePopup)});this.popup.bind("mouseover",function(){delayedFuncOpenSlow(self.showPopup)}).bind("mouseout",function(){delayedFuncCloseSlow(self.hidePopup)})}$(window).on("load resize orientationchange scroll",
this.setContentSize.call(this));this.btnClose.bind(self.options.clickEvent,function(e){self.hidePopup();e.preventDefault()})},outsideClickHandler:function(e){var targetNode=$((e.changedTouches?e.changedTouches[0]:e).target);if(!targetNode.closest(this.popup).length&&!targetNode.closest(this.btnOpen).length)this.hidePopup()},showPopup:function(){var self=this;this.holder.addClass(this.options.openClass);this.popup.css({display:"block"});var thisPopupBrandInput=this.popup.find("#brands-search-input");
if(thisPopupBrandInput.length)thisPopupBrandInput.focus();jQuery(window).on("keydown",function(e){if(e.keyCode===27){self.hidePopup();e.preventDefault()}});if(this.clickMode&&this.options.hideOnClickOutside&&!this.outsideHandlerActive){this.outsideHandlerActive=true;$(document).bind("click touchstart",this.outsideClickHandler)}this.setContentSize()},hidePopup:function(){this.holder.removeClass(this.options.openClass);this.popup.css({display:"none"});jQuery(window).off("keydown");if(this.clickMode&&
this.options.hideOnClickOutside&&this.outsideHandlerActive){this.outsideHandlerActive=false;$(document).unbind("click touchstart",this.outsideClickHandler)}},bind:function(f,scope,forceArgs){return function(){return f.apply(scope,forceArgs?[forceArgs]:arguments)}},setContentSize:function(){this.findContents();if(this.content.length===1&&this.footer.length===1){var headerSize=$(".header").height();var menuSize=$(".navigation").height();var contentSize=this.content.outerHeight();var paddingSize=$(".drop").outerHeight()-
$(".drop").height();var footerSize=this.footer.outerHeight();var winHeight=window.innerHeight-headerSize;if(contentSize)if(contentSize+footerSize>=winHeight){$(this).addClass;this.content.height(winHeight-footerSize-headerSize)}}}};var isTouchDevice=/MSIE 10.*Touch/.test(navigator.userAgent)||"ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch;$.fn.contentPopup=function(opt){return this.each(function(){new ContentPopup($.extend(opt,{holder:this}))})}})(jQuery);
(function(){var placeholderCollection=[];PlaceholderInput=function(){this.options={element:null,showUntilTyping:false,wrapWithElement:false,getParentByClass:false,showPasswordBullets:false,placeholderAttr:"value",inputFocusClass:"focus",inputActiveClass:"text-active",parentFocusClass:"parent-focus",parentActiveClass:"parent-active",labelFocusClass:"label-focus",labelActiveClass:"label-active",fakeElementClass:"input-placeholder-text"};placeholderCollection.push(this);this.init.apply(this,arguments)};
PlaceholderInput.refreshAllInputs=function(except){for(var i=0;i<placeholderCollection.length;i++)if(except!==placeholderCollection[i])placeholderCollection[i].refreshState()};PlaceholderInput.replaceByOptions=function(opt){var inputs=[].concat(convertToArray(document.getElementsByTagName("input")),convertToArray(document.getElementsByTagName("textarea")));for(var i=0;i<inputs.length;i++)if(inputs[i].className.indexOf(opt.skipClass)<0){var inputType=getInputType(inputs[i]);var placeholderValue=inputs[i].getAttribute("placeholder");
if(opt.focusOnly||opt.clearInputs&&(inputType==="text"||inputType==="email"||placeholderValue)||opt.clearTextareas&&inputType==="textarea"||opt.clearPasswords&&inputType==="password")new PlaceholderInput({element:inputs[i],focusOnly:opt.focusOnly,wrapWithElement:opt.wrapWithElement,showUntilTyping:opt.showUntilTyping,getParentByClass:opt.getParentByClass,showPasswordBullets:opt.showPasswordBullets,placeholderAttr:placeholderValue?"placeholder":opt.placeholderAttr})}};PlaceholderInput.prototype={init:function(opt){this.setOptions(opt);
if(this.element&&this.element.PlaceholderInst)this.element.PlaceholderInst.refreshClasses();else{this.element.PlaceholderInst=this;if(this.elementType!=="radio"||this.elementType!=="checkbox"||this.elementType!=="file"){this.initElements();this.attachEvents();this.refreshClasses()}}},setOptions:function(opt){for(var p in opt)if(opt.hasOwnProperty(p))this.options[p]=opt[p];if(this.options.element){this.element=this.options.element;this.elementType=getInputType(this.element);if(this.options.focusOnly)this.wrapWithElement=
false;else if(this.elementType==="password"&&this.options.showPasswordBullets&&!this.options.showUntilTyping)this.wrapWithElement=false;else this.wrapWithElement=this.elementType==="password"||this.options.showUntilTyping?true:this.options.wrapWithElement;this.setPlaceholderValue(this.options.placeholderAttr)}},setPlaceholderValue:function(attr){this.origValue=attr==="value"?this.element.defaultValue:this.element.getAttribute(attr)||"";if(this.options.placeholderAttr!=="value")this.element.removeAttribute(this.options.placeholderAttr)},
initElements:function(){if(this.wrapWithElement){this.fakeElement=document.createElement("span");this.fakeElement.className=this.options.fakeElementClass;this.fakeElement.innerHTML+=this.origValue;this.fakeElement.style.color=getStyle(this.element,"color");this.fakeElement.style.position="absolute";this.element.parentNode.insertBefore(this.fakeElement,this.element);if(this.element.value===this.origValue||!this.element.value){this.element.value="";this.togglePlaceholderText(true)}else this.togglePlaceholderText(false)}else if(!this.element.value&&
this.origValue.length)this.element.value=this.origValue;if(this.element.id){this.labels=document.getElementsByTagName("label");for(var i=0;i<this.labels.length;i++)if(this.labels[i].htmlFor===this.element.id){this.labelFor=this.labels[i];break}}this.elementParent=this.element.parentNode;if(typeof this.options.getParentByClass==="string"){var el=this.element;while(el.parentNode)if(hasClass(el.parentNode,this.options.getParentByClass)){this.elementParent=el.parentNode;break}else el=el.parentNode}},
attachEvents:function(){this.element.onfocus=bindScope(this.focusHandler,this);this.element.onblur=bindScope(this.blurHandler,this);if(this.options.showUntilTyping){this.element.onkeydown=bindScope(this.typingHandler,this);this.element.onpaste=bindScope(this.typingHandler,this)}if(this.wrapWithElement)this.fakeElement.onclick=bindScope(this.focusSetter,this)},togglePlaceholderText:function(state){if(!this.element.readOnly&&!this.options.focusOnly)if(this.wrapWithElement)this.fakeElement.style.display=
state?"":"none";else this.element.value=state?this.origValue:""},focusSetter:function(){this.element.focus()},focusHandler:function(){clearInterval(this.checkerInterval);this.checkerInterval=setInterval(bindScope(this.intervalHandler,this),1);this.focused=true;if(!this.element.value.length||this.element.value===this.origValue)if(!this.options.showUntilTyping)this.togglePlaceholderText(false);this.refreshClasses()},blurHandler:function(){clearInterval(this.checkerInterval);this.focused=false;if(!this.element.value.length||
this.element.value===this.origValue)this.togglePlaceholderText(true);this.refreshClasses();PlaceholderInput.refreshAllInputs(this)},typingHandler:function(){setTimeout(bindScope(function(){if(this.element.value.length){this.togglePlaceholderText(false);this.refreshClasses()}},this),10)},intervalHandler:function(){if(typeof this.tmpValue==="undefined")this.tmpValue=this.element.value;if(this.tmpValue!=this.element.value)PlaceholderInput.refreshAllInputs(this)},refreshState:function(){if(this.wrapWithElement)if(this.element.value.length&&
this.element.value!==this.origValue)this.togglePlaceholderText(false);else if(!this.element.value.length)this.togglePlaceholderText(true);this.refreshClasses()},refreshClasses:function(){this.textActive=this.focused||this.element.value.length&&this.element.value!==this.origValue;this.setStateClass(this.element,this.options.inputFocusClass,this.focused);this.setStateClass(this.elementParent,this.options.parentFocusClass,this.focused);this.setStateClass(this.labelFor,this.options.labelFocusClass,this.focused);
this.setStateClass(this.element,this.options.inputActiveClass,this.textActive);this.setStateClass(this.elementParent,this.options.parentActiveClass,this.textActive);this.setStateClass(this.labelFor,this.options.labelActiveClass,this.textActive)},setStateClass:function(el,cls,state){if(!el)return;else if(state)addClass(el,cls);else removeClass(el,cls)}};function convertToArray(collection){var arr=[];for(var i=0,ref=arr.length=collection.length;i<ref;i++)arr[i]=collection[i];return arr}function getInputType(input){return(input.type?
input.type:input.tagName).toLowerCase()}function hasClass(el,cls){return el.className?el.className.match(new RegExp("(\\s|^)"+cls+"(\\s|$)")):false}function addClass(el,cls){if(!hasClass(el,cls))el.className+=" "+cls}function removeClass(el,cls){if(hasClass(el,cls))el.className=el.className.replace(new RegExp("(\\s|^)"+cls+"(\\s|$)")," ")}function bindScope(f,scope){return function(){return f.apply(scope,arguments)}}function getStyle(el,prop){if(document.defaultView&&document.defaultView.getComputedStyle)return document.defaultView.getComputedStyle(el,
null)[prop];else if(el.currentStyle)return el.currentStyle[prop];else return el.style[prop]}})();
