var CheckoutMain=Class.create();
CheckoutMain.prototype={initialize:function(allForms){this.allForms=allForms},setLoadWaiting:function(flag){$("uni-main-loader-checkout").style.height=$("opcheckout-wrapper-main").clientHeight+"px";document.getElementById("uni-main-loader-checkout").style.display=flag?"block":"none";document.getElementById("sub-loader").style.display=flag?"block":"none"},save:function(){var validators=[];for(i=0;i<this.allForms.length;i++)validators[i]=new Validation(this.allForms[i]);syncShipping(false);validators[2].validate();
jQuery("#advice-validate-billing-city-chosen").hide();this.shippingMethodValidate();if(validators[0].validate()&&validators[1].validate()&&validators[2].validate()&&this.shippingMethodValidate()&&this.paymentMethodValidate()&&(validators[3]?validators[3].validate():true))reviewFinal.save()},setShippingDifferent:function(divId,isDiff){document.getElementById(divId).style.display=isDiff?"none":"block"},setStepResponse:function(response){if(response.update_section){if($("checkout-"+response.update_section.name+
"-load"))$("checkout-"+response.update_section.name+"-load").update(response.update_section.html);return true}return false},loadReview:function(){},shippingMethodValidate:function(){if(!canShip())return true;var methods=document.getElementsByName("shipping_method");if(methods.length==0){jQuery("#advice-validate-billing-city-chosen").text(Translator.translate("This is a required field.")).show();return false}if(methods[0].value)return true;alert(Translator.translate("Please specify shipping method."));
return false},paymentMethodValidate:function(){var methods=document.getElementsByName("payment[method]");if(methods.length==0){alert(Translator.translate("Your order can not be completed at this time as there is no payment methods available for it."));return false}if(methods[0].value)return true;alert(Translator.translate("Please specify payment method."));return false}};var Billing=Class.create();
Billing.prototype={initialize:function(form,addressUrl,saveUrl){this.form=form;if($(this.form))$(this.form).observe("submit",function(event){this.save();Event.stop(event)}.bind(this));this.addressUrl=addressUrl;this.saveUrl=saveUrl;this.onAddressLoad=this.fillForm.bindAsEventListener(this);this.onSave=this.nextStep.bindAsEventListener(this);this.onFail=this.ajaxFailed.bindAsEventListener(this)},setAddress:function(addressId){if(addressId)request=new Ajax.Request(this.addressUrl+addressId,{method:"get",
onSuccess:this.onAddressLoad,onFailure:this.onFail});else this.fillForm(false)},newAddress:function(isNew){if(isNew){this.resetSelectedAddress();Element.show("billing-imformation-fields")}else Element.hide("billing-imformation-fields");billing.save()},resetSelectedAddress:function(){var selectElement=$("billing-address-select");if(selectElement)selectElement.value=""},fillForm:function(transport){var elementValues={};if(transport&&transport.responseText)try{elementValues=eval("("+transport.responseText+
")")}catch(e){elementValues={}}else this.resetSelectedAddress();arrElements=Form.getElements(this.form);for(var elemIndex in arrElements)if(arrElements[elemIndex].id){var fieldName=arrElements[elemIndex].id.replace(/^billing:/,"");arrElements[elemIndex].value=elementValues[fieldName]?elementValues[fieldName]:"";if(fieldName=="country_id"&&billingForm)billingForm.elementChildLoad(arrElements[elemIndex])}},setUseForShipping:function(flag){$("shipping:same_as_billing").checked=flag},save:function(){checkout.setLoadWaiting("billing");
var requestParametrs=Form.serialize(this.form)+"&billing[city]="+$$('select[name="billing[city]"]').first().value;var request=new Ajax.Request(this.saveUrl,{method:"post",onComplete:this.onComplete,onSuccess:this.onSave,onFailure:this.onFail,parameters:requestParametrs})},resetLoadWaiting:function(transport){checkout.setLoadWaiting(false)},nextStep:function(transport){checkout.setLoadWaiting(false);if(transport&&transport.responseText)try{response=eval("("+transport.responseText+")")}catch(e){response=
{}}else{console.log("Empty response received");return false}if(response.error){if(typeof response.message=="string")alert(response.message);else{if(window.billingRegionUpdater)billingRegionUpdater.update();alert(response.message.join("\n"))}return false}if((response.goto_section=="shipping"||response.goto_section=="shipping_method")&&checkout.setStepResponse(response));if(response.goto_section=="shipping")if(!canShip())window.location=window.location;else shippingStep.save();else payment.loadPaymentMethods()},
ajaxFailed:function(){alert("Billing Ajax Failed!")}};var ShippingStep=Class.create();
ShippingStep.prototype={initialize:function(shippingForm,saveUrl,methodsUrl){this.shippingForm=shippingForm;this.saveUrl=saveUrl;this.methodsUrl=methodsUrl;this.onSave=this.nextStep.bindAsEventListener(this);this.onFail=this.ajaxFailed.bindAsEventListener(this)},setSameAsBilling:function(flag){if(flag)this.syncWithBilling()},syncWithBilling:function(){$("billing-address-select")&&this.newAddress(!$("billing-address-select").value);if(!$("billing-address-select")||!$("billing-address-select").value){arrElements=
Form.getElements(this.shippingForm);for(var elemIndex in arrElements)if(arrElements[elemIndex].id){var sourceField=$(arrElements[elemIndex].id.replace(/^shipping:/,"billing:"));if(sourceField)arrElements[elemIndex].value=sourceField.value}shippingRegionUpdater.update();$("shipping:region_id").value=$("billing:region_id").value;$("shipping:region").value=$("billing:region").value}else $("shipping-address-select").value=$("billing-address-select").value},save:function(){checkout.setLoadWaiting(true);
var request=new Ajax.Request(this.saveUrl,{method:"post",onComplete:this.onComplete,onSuccess:this.onSave,onFailure:this.onFail,parameters:Form.serialize(this.shippingForm)})},newAddress:function(isNew){if(isNew){this.resetSelectedAddress();Element.show("shipping-imformation-fields")}else Element.hide("shipping-imformation-fields");shipping.setSameAsBilling(false)},resetSelectedAddress:function(){var selectElement=$("shipping-address-select");if(selectElement)selectElement.value=""},nextStep:function(transport){if(transport&&
transport.responseText)try{response=eval("("+transport.responseText+")")}catch(e){response={}}if(response.error){if(typeof response.message=="string")alert(response.message);else{if(window.shippingRegionUpdater)shippingRegionUpdater.update();alert(response.message.join("\n"))}checkout.setLoadWaiting(false);return false}if(checkout.setStepResponse(response));checkout.setLoadWaiting(false);payment.loadPaymentMethods();reviewStep.getReview()},ajaxFailed:function(){alert("ShippingStep Ajax Failed!")}};
var ShippingMethodStep=Class.create();
ShippingMethodStep.prototype={initialize:function(shippingMethodForm,saveUrl,actionUrl){this.shippingMethodForm=shippingMethodForm;this.actionUrl=actionUrl;this.saveUrl=saveUrl;this.onSave=this.nextStep.bindAsEventListener(this);this.onFail=this.ajaxFailed.bindAsEventListener(this);this.onLoad=this.setShippingMethod.bindAsEventListener(this)},save:function(){checkout.setLoadWaiting(true);var request=new Ajax.Request(this.saveUrl,{method:"post",onComplete:this.onComplete,onSuccess:this.onSave,onFailure:this.onFail,
parameters:Form.serialize(this.shippingMethodForm)})},nextStep:function(transport){if(transport&&transport.responseText)try{response=eval("("+transport.responseText+")");$("opcheckout-payment-method").update(response.update_section.html)}catch(e){response={}}if(response.redirect){location.href=response.redirect;return}if(response.error){alert(response.message);return false}checkout.setLoadWaiting(false)},loadShippingMethods:function(){checkout.setLoadWaiting(true);var request=new Ajax.Request(this.actionUrl,
{method:"post",onSuccess:this.onLoad,onFailure:this.onFail,parameters:Form.serialize(this.shippingMethodForm)})},setShippingMethod:function(transport){if(transport&&transport.responseText)try{response=eval("("+transport.responseText+")")}catch(e){response={}}if(response.html)$("checkout-shipping-method-load").update(response.html);reviewStep.getReview()},ajaxFailed:function(){alert("ShippingMethodStep Ajax Failed!")}};var Payment=Class.create();
Payment.prototype={initialize:function(form,saveUrl,actionUrl){this.form=form;this.saveUrl=saveUrl;this.actionUrl=actionUrl;this.onSave=this.nextStep.bindAsEventListener(this);this.onLoad=this.setPaymentMethod.bindAsEventListener(this);this.onFail=this.ajaxFailed.bindAsEventListener(this)},init:function(){var elements=Form.getElements(this.form);var method=null;if(this.currentMethod&&$("p_method_"+this.currentMethod))$("p_method_"+this.currentMethod).checked=true;for(var i=0;i<elements.length;i++)if(elements[i].name==
"payment[method]"){if(elements[i].checked)method=elements[i].value}else elements[i].disabled=true;if(method)this.switchMethod(method)},switchMethod:function(method){if(this.currentMethod&&$("payment_form_"+this.currentMethod)){var form=$("payment_form_"+this.currentMethod);form.style.display="none";var elements=form.select("input","select","textarea");for(var i=0;i<elements.length;i++)elements[i].disabled=true}if($("payment_form_"+method)){var form=$("payment_form_"+method);form.style.display="";
var elements=form.select("input","select","textarea");for(var i=0;i<elements.length;i++)elements[i].disabled=false}if(method)this.currentMethod=method},validate:function(){var methods=document.getElementsByName("payment[method]");if(methods.length==0){alert(Translator.translate("Your order can not be completed at this time as there is no payment methods available for it."));return false}for(var i=0;i<methods.length;i++)if(methods[i].checked)return true;alert(Translator.translate("Please specify payment method."));
return false},save:function(){var validator=new Validation(this.form);if(this.validate()&&validator.validate())var request=new Ajax.Request(this.saveUrl,{method:"post",onComplete:this.onComplete,onSuccess:this.onSave,onFailure:this.onFail,parameters:Form.serialize(this.form)});else alert("Payment Method validation fail.")},nextStep:function(transport){if(transport&&transport.responseText)try{response=eval("("+transport.responseText+")")}catch(e){response={}}if(response.error){if(response.fields){var fields=
response.fields.split(",");for(var i=0;i<fields.length;i++){var field=null;if(field=$(fields[i]))Validation.ajaxError(field,response.error)}return}alert(response.error);return}if(checkout.setStepResponse(response));},ajaxFailed:function(){alert("Payment Ajax Failed!")},loadPaymentMethods:function(){checkout.setLoadWaiting(true);var request=new Ajax.Request(this.actionUrl,{method:"post",onComplete:this.onComplete,onSuccess:this.onLoad,onFailure:this.onFail,parameters:Form.serialize(this.form)})},setPaymentMethod:function(transport){if(transport&&
transport.responseText)try{response=eval("("+transport.responseText+")")}catch(e){response={}}if(response.html){$("opcheckout-payment-method").update(response.html);if(response.method)this.currentMethod=response.method;this.init();resetPaymentEvents()}jQuery("#payment-method").chosen({disable_search:true,inherit_select_classes:true});checkout.setLoadWaiting(false)}};var ReviewStep=Class.create();
ReviewStep.prototype={initialize:function(saveUrl){this.saveUrl=saveUrl;this.onSave=this.nextStep.bindAsEventListener(this);this.onFail=this.ajaxFailed.bindAsEventListener(this)},getReview:function(){checkout.setLoadWaiting(true);var request=new Ajax.Request(this.saveUrl,{method:"post",onComplete:this.onComplete,onSuccess:this.onSave,onFailure:this.onFail,parameters:{json:1}})},getReviewDiscountRecalculation:function(bonusPayment,bonusBalance){checkout.setLoadWaiting(true);new Ajax.Request(this.saveUrl,
{method:"post",onComplete:this.onComplete,onSuccess:this.onSave,onFailure:this.onFail,parameters:{bonus_payment:bonusPayment,bonus_balance:bonusBalance}})},getReviewUpdate:function(update){checkout.setLoadWaiting(true);new Ajax.Request(this.saveUrl,{method:"post",onComplete:this.onComplete,onSuccess:this.onSave,onFailure:this.onFail,parameters:{update:update}})},nextStep:function(transport){var response=transport.responseText.evalJSON();$$("#checkout-product-container li").each(function(element){var btnRemove=
element.select("span.btn-remove").first();var itemInput=element.select("input.opcheckout-item-qty").first();var itemIndex=itemInput.readAttribute("data-item-index");if(response.products[itemIndex]===undefined){element.select("img").first().setStyle({opacity:.5});element.select("a.product-name").first().setStyle({color:"#8d877b","text-decoration":"line-through"});element.select("input.opcheckout-item-qty").first().setValue(0).setAttribute("data-deleted",1);btnRemove.hide()}else{var valuenow=response.products[itemIndex].qty;
var formatpricenow=response.products[itemIndex].format_price;element.select("img").first().setStyle({opacity:1});element.select("a.product-name").first().setStyle({color:"#a97b2a","text-decoration":"none"});element.select("input.opcheckout-item-qty").first().setValue(valuenow);$$("#opcheckout-item-"+itemIndex+" .price").first().replace(formatpricenow);btnRemove.show()}});var html="";response.totals.forEach(function(item,i,arr){var minus="",template="",id="";if(item["class"]=="discount"){minus="\u2212 ";
template='<span class="price">'+minus+"</span>";id='id="discount"'}if(item["class"]=="grand_total"||item["title"]=="\u0418\u0442\u043e\u0433\u043e \u043a \u043e\u043f\u043b\u0430\u0442\u0435"){id='id="grand_total"';template=""}if(item["class"]=="subtotal"){id='id="subtotal_price"';template=""}if(item["class"]=="bonus_payment"){item["class"]="rewards_spend";id='id="rewards_spend"'}html+='<tr class="'+item["class"]+'"><td>'+item.title+"</td><td "+id+">"+template+""+item.price+"</td></tr>"});$("price-totals").update(html);
if(response.giftwrap=="true")$("opcheckout_order_giftwrap_table").show();else $("opcheckout_order_giftwrap_table").hide();checkout.setLoadWaiting(false)},ajaxFailed:function(){alert("ReviewStep Ajax Failed!")},isSuccess:false};var ReviewFinal=Class.create();
ReviewFinal.prototype={initialize:function(saveUrl,successUrl,agreementsForm){this.saveUrl=saveUrl;this.successUrl=successUrl;this.agreementsForm=agreementsForm;this.onSave=this.nextStep.bindAsEventListener(this);this.onFail=this.ajaxFailed.bindAsEventListener(this)},urlParse:function(str){var result=[];var keyValues=str.split("&");var keys=[];for(var i=0;i<keyValues.length;i++){var parts=keyValues[i].split("=");var key=parts[0];var value=parts[1];if(keys.indexOf(key)>-1)continue;result.push(key+
"="+value);keys.push(key)}return result.join("&")},save:function(){checkout.setLoadWaiting(true);var element=$("opcheckout_order_comment");if(!element==null)$("hidden_opcheckout_order_comment").value=$("opcheckout_order_comment").value;var params="";for(i=0;i<checkout.allForms.length;i++)params=params+(params!=""?"&":"")+Form.serialize(checkout.allForms[i]);params=this.urlParse(params);params.save=true;var request=new Ajax.Request(this.saveUrl,{method:"post",parameters:params,onComplete:this.onComplete,
onSuccess:this.onSave,onFailure:this.onFail})},nextStep:function(transport){if(transport&&transport.responseText){try{response=eval("("+transport.responseText+")")}catch(e){response={}}if(response.redirect){location.href=response.redirect;return}if(response.success){this.isSuccess=true;window.location=this.successUrl}else if(!canShip()&&response.is_virtual==0)window.location=window.location;else{var msg=response.error_messages;if(typeof msg=="object")msg=msg.join("\n");alert(msg,"123123123123123")}}checkout.setLoadWaiting(false)},
ajaxFailed:function(){alert("ReviewFinal Ajax Failed!!");$("opcheckout-place-order-button").onclick="checkout.save()"},isSuccess:false};var QuoteItems=Class.create();
QuoteItems.prototype={initialize:function(addUrl,removeUrl,changeQtyUrl){this.changeQtyUrl=changeQtyUrl;this.addUrl=addUrl;this.removeUrl=removeUrl;this.onSuccess=this.reloadReviewAndShippingMethods.bindAsEventListener(this);this.onFail=this.ajaxFailed.bindAsEventListener(this)},removeItem:function(item_id){checkout.setLoadWaiting(true);var request=new Ajax.Request(this.removeUrl,{method:"post",onSuccess:this.onSuccess,onFailure:this.onFail,parameters:{item_id:item_id}})},addItem:function(product_id,
qty){checkout.setLoadWaiting(true);var request=new Ajax.Request(this.addUrl,{method:"post",onSuccess:this.onSuccess,onFailure:this.onFail,parameters:{product:product_id,qty:qty}})},changeItemQty:function(item_id,item_qty){checkout.setLoadWaiting(true);var request=new Ajax.Request(this.changeQtyUrl,{method:"post",onSuccess:this.onSuccess,onFailure:this.onFail,parameters:{item_id:item_id,item_qty:item_qty}})},changeItemQtyOrRemove:function(item_id,item_qty,deleted,product_id){if(item_qty>0&&deleted!=
1)this.changeItemQty(item_id,item_qty);else if(item_qty>0&&deleted==1)this.addItem(product_id,item_qty);else this.removeItem(item_id)},reloadReviewAndShippingMethods:function(transport){if(transport&&transport.responseText)response=eval("("+transport.responseText+")");$$("#checkout-product-container li").each(function(element){var currentProductId=element.select("input.opcheckout-item-qty").first().readAttribute("data-product-id");if(currentProductId==response.product_id){element.select("input.opcheckout-item-qty").first().setAttribute("data-item-index",
response.item);element.select("input.opcheckout-item-qty").first().removeAttribute("data-deleted");element.select("span.btn-remove").first().setAttribute("data-item-index",response.item)}});shippingMethodStep.loadShippingMethods();if(response.redirect)window.location.href=response.redirect;if(response.error&&response.message)alert(response.message)},ajaxFailed:function(){checkout.setLoadWaiting(false);alert("QuoteItems Ajax Failed!")}};
if(!String.prototype.trim)String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};function canShip(){return parseInt($("opcheckout-canShip").value)?true:false}
function resetPaymentEvents(){function toggleToolTip(event){if($("payment-tool-tip")){$("payment-tool-tip").setStyle({top:Event.pointerY(event)-320+"px"});$("payment-tool-tip").toggle()}Event.stop(event)}if($("payment-tool-tip-close"))Event.observe($("payment-tool-tip-close"),"click",toggleToolTip);$$(".cvv-what-is-this").each(function(element){Event.observe(element,"click",toggleToolTip)})};
