function showForm(){document.getElementById("form_rating").style.display="block";document.getElementById("hide_button").style.display="inline-block";document.getElementById("add_rating_button").style.display="inline-block";document.getElementById("create_button").style.display="none"}
function hideForm(){document.getElementById("form_rating").style.display="none";document.getElementById("hide_button").style.display="none";document.getElementById("add_rating_button").style.display="none";document.getElementById("create_button").style.display="inline-block"}
jQuery(function($){var productAddToCartForm=new VarienForm("product_addtocart_form");productAddToCartForm.submit=function(button,url){console.log("test BUY");if(this.validator.validate()){var form=this.form;var oldUrl=form.action;if(url)form.action=url;var e=null;try{this.form.submit()}catch(e$0){}this.form.action=oldUrl;if(e)throw e;if(button&&button!="undefined")button.disabled=true}}.bind(productAddToCartForm);productAddToCartForm.submitLight=function(button,url){if(this.validator){var nv=Validation.methods;
delete Validation.methods["required-entry"];delete Validation.methods["validate-one-required"];delete Validation.methods["validate-one-required-by-name"];for(var methodName in Validation.methods)if(methodName.match(/^validate-datetime-.*/i))delete Validation.methods[methodName];if(this.validator.validate()){if(url)this.form.action=url;this.form.submit()}Object.extend(Validation.methods,nv)}}.bind(productAddToCartForm);var image=$("#image"),moreViews=$("#thumbnails"),items=moreViews.children();moreViews.on("click",
"a.fancybox-thumb",function(e){e.preventDefault();var a=$(this),holder=a.parent(),imgSrc=a.attr("href");if(!holder.hasClass("active")){items.removeClass("active");holder.addClass("active");if(imgSrc.indexOf("#"))image.attr("src",imgSrc)}return false});function setVerticalSlider(){var posVertical=0,posHorizontal=0,it=$(".vertical-slider.switcher"),container=it.find(".vertical-container"),containerHeight=container.height(),containerWidth=container.width(),content=container.find("ul#thumbnails"),contentHeight=
content.outerHeight(true),contentWidth=content.outerWidth(true),stepVertical=content.find("li").eq(0).outerHeight(true),stepHorizontal=content.find("li").eq(0).outerWidth(true)+3,moveDown=function(){posVertical-=stepVertical;if(contentHeight+posVertical-containerHeight<0)posVertical=containerHeight-contentHeight;content.css("top",posVertical+"px")},moveUp=function(){posVertical+=stepVertical;if(posVertical>0)posVertical=0;content.css("top",posVertical+"px")},moveRight=function(){posHorizontal-=stepHorizontal;
if(contentWidth+posHorizontal-containerWidth<0)posHorizontal=containerWidth-contentWidth;content.css("left",posHorizontal+"px")},moveLeft=function(){posHorizontal+=stepHorizontal;if(posHorizontal>0)posHorizontal=0;content.css("left",posHorizontal+"px")};var setVerticalOrientation=function(){var allHeight=it.outerHeight();content.css({width:"",left:"",top:"","margin-left":"","margin-right":""});contentHeight=content.outerHeight(true);posVertical=0;if(contentHeight<=allHeight){it.find(".up-arrow").hide();
it.find(".down-arrow").hide();container.height(allHeight)}else{it.find(".up-arrow").off("click").show().css("display","").click(moveUp);it.find(".down-arrow").off("click").show().css("display","").click(moveDown)}},setHorizontalOrientation=function(){posHorizontal=0;stepHorizontal=content.find("li").eq(0).outerWidth(true);contentWidth=content.find("li").size()*stepHorizontal;containerWidth=container.width();content.css({width:"",left:"",top:"",height:""});content.width(contentWidth);container.css("height",
"");if(contentWidth<=containerWidth){it.find(".up-arrow").hide();it.find(".down-arrow").hide();content.css({"margin-left":"auto","margin-right":"auto"})}else{it.find(".up-arrow").off("click").show().css("display","").click(moveLeft);it.find(".down-arrow").off("click").show().css("display","").click(moveRight)}};var query2="screen and (max-width: 1365px)",mql2=window.matchMedia(query2),changeOrientation=function(mql){if(mql.matches)setHorizontalOrientation();else setVerticalOrientation()};mql2.addListener(changeOrientation);
changeOrientation(mql2)}setVerticalSlider();function openProductImagePreview(e){e.preventDefault();var clone=$("#product-image-gallery-fancy-template").clone().attr({style:"",id:"big-image"}),big=clone.find("#__brand-carousel").attr("id","brand-carousel").find(".slideset"),thumb=clone.find("#__brand-carousel-nav").attr("id","brand-carousel-nav").css({position:"relative",bottom:"auto",height:"60px"}).find(".slideset"),initSlick=function(){var speed=300;big.slick({initialSlide:2,slidesToShow:1,slidesToScroll:1,
fade:true,speed:speed,asNavFor:thumb});thumb.slick({initialSlide:2,slidesToShow:7,slidesToScroll:1,speed:speed,asNavFor:big,centerMode:true,focusOnSelect:true});$(".popup-holder.fancybox-inner").css({overflow:"hidden"});function myGoTo(index){big.slickSetOption("speed",1);big.css("opacity",0);var it=$(this),safetyCounter=0;spike=function(){var currentSlide=big.slickCurrentSlide();if(currentSlide==index||safetyCounter>100){big.slickSetOption("speed",speed);big.css("opacity",1);return}big.css("opacity",
1/(1+Math.abs(currentSlide-index)));if(currentSlide>index)big.slickPrev();else big.slickNext();setTimeout(spike,10);safetyCounter++};spike();return false}myGoTo($("#thumbnails li.active").first().index());$("#brand-carousel-nav.brand-carousel-nav.not-enough-thumbs div.slide > img").click(function(e){e.preventDefault();var it=$(this),index=parseInt(it.data("index"));myGoTo(index);return false})};if(jQuery("#image").width()<jQuery("#image").data("max-width"))jQuery.fancybox.open({padding:0,content:clone,
minWidth:600,minHeight:600,tpl:{wrap:'<div class="fancybox-wrap" tabIndex="-1">'+'<div class="fancybox-skin">'+'<div class="fancybox-outer">'+'<div class="fancybox-inner">'+"</div></div></div></div>",closeBtn:'<a title="Close" class="fancybox-item fancybox-close" href="javascript:;"></a>'},afterLoad:function(current,previous){setTimeout(initSlick,100)}});return false}function openProductImagePreviewBindEvent(arguments){if(jQuery("#image").width()<jQuery("#image").data("max-width"))jQuery("#image").attr("style",
"cursor: pointer;");else jQuery("#image").attr("style","cursor: default;");image.on("click",openProductImagePreview)}jQuery(window).on("resize",function(){openProductImagePreviewBindEvent()});jQuery(document).ready(function(){openProductImagePreviewBindEvent()});jQuery("#description_go").click(function(){window.location.hash="#descript_stop"});jQuery("#collateral div.wide-gallery").slick({infinite:false,dots:false,speed:300,slidesToShow:3,slidesToScroll:3});jQuery("#cswatch-color li a > span").hover(function(){$this=
jQuery(this);$this.append("<span>"+$this.attr("title")+"</span>")},function(){$this=jQuery(this);$this.find("span").remove()});jQuery(".show_all").click(function(){jQuery(this).remove();jQuery("#cswatch-color li:gt(2)").show()});var sidebar=$("#product-sidebar"),footer=$("#footer"),w=$(window),fh=footer.outerHeight();sidebarCss={top:sidebar.css("top"),bottom:sidebar.css("bottom")};var calculateSidebarOffset=function(e){var st=w.scrollTop(),dh=$(document).height(),wh=w.height(),delta=dh-(st+wh)-fh;
if(delta<0)sidebar.css({top:delta+"px",bottom:Math.abs(delta)+"px"});else sidebar.css({top:sidebarCss.top,bottom:sidebarCss.bottom})};var vh=$("#product-viewed-holder"),v=$("#product-viewed");btn=vh.find("a.btn-viewed");btn.on("click",function(e){e.preventDefault();if(!vh.hasClass("active"))v.slideDown(function(){vh.addClass("active")});else v.slideUp(function(){vh.removeClass("active")})});v.find(".wide-gallery-top").slick({infinite:true,dots:false,speed:300,slidesToShow:7,slidesToScroll:7,responsive:[{breakpoint:1950,
settings:{slidesToShow:4,slidesToScroll:1}},{breakpoint:1600,settings:{slidesToShow:3,slidesToScroll:3}},{breakpoint:1280,settings:{slidesToShow:2,slidesToScroll:2}},{breakpoint:415,settings:{slidesToShow:1,slidesToScroll:1}}]});jQuery(".socials").on("click","a",shareThisProduct);function getPageShareData(){var url=location.href;var title=jQuery(".h1-type").text()+" "+jQuery(".h1-brand").text()+" "+jQuery(".h1-name").text();var description=jQuery("#detailed-description .big > p").text();var maxLength=
200;var trimmedString=description.substr(0,maxLength);description=trimmedString.substr(0,Math.min(trimmedString.length,trimmedString.lastIndexOf(" ")));description=description+" ...";var image=jQuery("img#image").attr("src");return{url:url,title:title,description:description,image:image}}function shareThisProduct(event){event.preventDefault();var data=getPageShareData();var url;if(jQuery(event.currentTarget).data("id")=="vk"){url="http://vk.com/share.php?url="+data.url+"&title="+data.title+"&description="+
data.description+"&image="+data.image;window.open(url,"","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600")}else if(jQuery(event.currentTarget).data("id")=="gl"){url="https://plus.google.com/share?url="+data.url+"&title="+data.title+"&description="+data.description+"&image="+data.image;window.open(url,"","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600")}else if(jQuery(event.currentTarget).data("id")=="tw"){url="https://twitter.com/intent/tweet?url="+
data.url+"&text="+data.title+". "+data.description;window.open(url,"","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600")}else if(jQuery(event.currentTarget).data("id")=="fb"){url="https://www.facebook.com/sharer/sharer.php?u="+data.url+"&title="+data.title+"&description="+data.description+"&image="+data.image;window.open(url,"","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600")}}jQuery("#related-products div.wide-gallery-top").slick({infinite:false,
dots:false,speed:300,slidesToShow:5,slidesToScroll:5,responsive:[{breakpoint:1700,settings:{slidesToShow:4,slidesToScroll:4}},{breakpoint:1500,settings:{slidesToShow:3,slidesToScroll:3}},{breakpoint:1180,settings:{slidesToShow:2,slidesToScroll:2}},{breakpoint:415,settings:{slidesToShow:1,slidesToScroll:1}}]});$(document).ready(function(){if(localStorage.productListUrl&&localStorage.productListUrl.indexOf("catalogsearch")==-1)$(".product-back-button").show().find("a").attr("href",localStorage.productListUrl+
"#loaded")})});
